# Basic environment for Py-ART.
name: pyart_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - wradlib
  - cartopy
  - arm_pyart
  - xarray
  - xradar
  - mda-xdrlib
  - pip
  - pip:
    - wheel
    - watchdog
    - flake8
    - tox
    - coverage
    - Sphinx
    - twine
    - pytest
    - black
    - isort
    - pre_commit
