name: pyart-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - numpy
  - scipy
  - matplotlib
  - pandas
  - netcdf4
  - pytest
  - trmm_rsl
  - wradlib
  - cartopy
  - cvxopt
  - xarray
  - sphinx
  - ipython
  - pandoc
  - netcdf4
  - pytest
  - coin-or-cbc
  - pkg-config
  - Cython
  - fsspec
  - s3fs
  - pip
  - pip:
      - pydata-sphinx-theme<0.9.0
      - sphinx_gallery
      - sphinx-copybutton
      - myst_nb
      - ablog
      - nbsphinx
      - pooch
      - versioneer
