name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - gdal
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - basemap
  - trmm_rsl
  - wradlib
  - cartopy
  - cvxopt
  - xarray
