name: pyart-dev
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - gdal
  - netcdf4
  - pytest
  - wradlib
  - cartopy
  - cvxopt
  - xarray
  - pytest-cov
  - pytest-mpl
  - coveralls
  - flake8
  - Cython
  - fsspec
  - glpk
  - cftime
  - setuptools
  - shapely<1.8.3
  - pip
  - pip:
    - cibuildwheel
    - pooch
    - versioneer
