name: testenv
channels:
  - jjhelmus   # required until conda-forge trmm_rsl fixed
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - nose
  - basemap
  - trmm_rsl
  - wradlib
  - cartopy
